/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rdphouses;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author tholithemba
 */
public class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    Registration reg = new Registration();
    Validation v = new Validation();
    GenerateRandomChar grc = new GenerateRandomChar();

    
    
    public Administrator() {
        initComponents();
    }
    

    private void setValues(){
        reg.setFirstname(admin_firstname.getText());
        reg.setLastname(admin_lastname.getText());
        reg.setUsername(grc.generateUsername());
        reg.setPassword(grc.generatePassword());
        reg.setEmail(txtadminEmail.getText());
    }
    
    private boolean validateInput()
    {
        
        if(reg.getFirstname().equals(""))
            return outputStatement(" firstname");
        
        if(reg.getLastname().equals(""))
            return outputStatement(" lastname");
        
        if(reg.getEmail().equals(""))
            return outputStatement(" email address");
        
        return true;
    }
    
    private boolean outputStatement(String name)
    {
        confirmation.setForeground(Color.red);
        confirmation.setText("enter"+name);
        clearCells();
        return false;
    }
    
    private boolean emailExist()
    {
        String query_statement = "select* from ADMINISTRATOR where admin_email=?";
        boolean exist = v.checkUniqueness(query_statement, reg.getEmail());
        if(exist)
           return !outputStatement("ed email already exist");

        return exist;
    }
    
    private boolean usernameExist()
    {
        String query_statement = "select* from ADMINISTRATOR where admin_username=?";
        boolean exist = v.checkUniqueness(query_statement, reg.getUsername());
        if(exist)
           return !outputStatement("ed username already exist");

        return exist;
    }
    
   
    private void createAdministrator()
    {
        PreparedStatement ps;
        String query_statement = "INSERT INTO ADMINISTRATOR( admin_firstname, "
                + " admin_lastname, admin_email, admin_username "
                + ",admin_password) VALUES (?,?,?,?,?)";
        
        try
        {
            ps = Connect2database.getConnection().prepareStatement(query_statement);
            
            ps.setString(1, reg.getFirstname());
            ps.setString(2, reg.getLastname());
            ps.setString(3, reg.getEmail());
            ps.setString(4, reg.getUsername());
            ps.setString(5, reg.getPassword());
            
            if(ps.executeUpdate() > 0)
            {
                confirmation.setText("data captured successfully");
                clearCells();
            }
            
        }catch(SQLException sq)
        {
            sq.getStackTrace();
        }
        
    }
    
    private void loginDetails(){
        JOptionPane.showMessageDialog(null, "username: "+reg.getUsername()+
                " \n passord: "+reg.getPassword());
    }
    
    private void clearCells()
    {
        admin_firstname.setText("");
        admin_lastname.setText("");
        txtadminEmail.setText("");
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        lblname = new java.awt.Label();
        label3 = new java.awt.Label();
        AdminBackToLogin = new javax.swing.JLabel();
        closeAdmin = new javax.swing.JLabel();
        confirmation = new java.awt.Label();
        AdminRegistration = new javax.swing.JButton();
        admin_firstname = new javax.swing.JTextField();
        admin_lastname = new javax.swing.JTextField();
        txtadminEmail = new javax.swing.JTextField();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(53, 66, 74));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 73, 29), 3));

        label1.setBackground(new java.awt.Color(53, 66, 74));
        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("Lastname");

        lblname.setBackground(new java.awt.Color(53, 66, 74));
        lblname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblname.setForeground(java.awt.Color.white);
        lblname.setText("Firstname");

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setForeground(java.awt.Color.white);
        label3.setText("Administrator");

        AdminBackToLogin.setBackground(new java.awt.Color(53, 66, 74));
        AdminBackToLogin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        AdminBackToLogin.setForeground(java.awt.Color.white);
        AdminBackToLogin.setText("Back");
        AdminBackToLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 74), 0));
        AdminBackToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminBackToLoginMouseClicked(evt);
            }
        });

        closeAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rdphouses/close.png"))); // NOI18N
        closeAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeAdminMouseClicked(evt);
            }
        });

        confirmation.setAlignment(java.awt.Label.CENTER);
        confirmation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        confirmation.setForeground(java.awt.Color.green);

        AdminRegistration.setBackground(java.awt.Color.blue);
        AdminRegistration.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        AdminRegistration.setForeground(java.awt.Color.white);
        AdminRegistration.setText("Register");
        AdminRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminRegistrationMouseClicked(evt);
            }
        });

        label2.setBackground(new java.awt.Color(53, 66, 74));
        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(java.awt.Color.white);
        label2.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AdminBackToLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(257, 257, 257))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AdminRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(admin_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtadminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(admin_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(306, 306, 306))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtadminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(AdminRegistration)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeAdminMouseClicked
        System.exit(0); 
    }//GEN-LAST:event_closeAdminMouseClicked

    private void AdminBackToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBackToLoginMouseClicked
        new AdminAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminBackToLoginMouseClicked

    private void AdminRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminRegistrationMouseClicked
        
        setValues();
        
        if(!validateInput())return;
        if(emailExist())return;
        if(usernameExist())return;
        createAdministrator();
        loginDetails();
    }//GEN-LAST:event_AdminRegistrationMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminBackToLogin;
    private javax.swing.JButton AdminRegistration;
    private javax.swing.JTextField admin_firstname;
    private javax.swing.JTextField admin_lastname;
    private javax.swing.JLabel closeAdmin;
    private java.awt.Label confirmation;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label lblname;
    private javax.swing.JTextField txtadminEmail;
    // End of variables declaration//GEN-END:variables
}
