/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rdphouses;

/**
 *
 * @author tholithemba
 */
public class AdminAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AdminAdmin
     */
    public AdminAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteAdmin = new javax.swing.JLabel();
        createAdmin = new javax.swing.JLabel();
        updateAdmin = new javax.swing.JLabel();
        closeAdminAdmin = new javax.swing.JLabel();
        BackTAdminHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(53, 66, 74));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 73, 29), 3));

        deleteAdmin.setBackground(new java.awt.Color(53, 66, 74));
        deleteAdmin.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        deleteAdmin.setForeground(java.awt.Color.white);
        deleteAdmin.setText("Delete Administrator");
        deleteAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAdminMouseClicked(evt);
            }
        });

        createAdmin.setBackground(new java.awt.Color(53, 66, 74));
        createAdmin.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        createAdmin.setForeground(java.awt.Color.white);
        createAdmin.setText("Create Administrator");
        createAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAdminMouseClicked(evt);
            }
        });

        updateAdmin.setBackground(new java.awt.Color(53, 66, 74));
        updateAdmin.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        updateAdmin.setForeground(java.awt.Color.white);
        updateAdmin.setText("Update Administrator");
        updateAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateAdminMouseClicked(evt);
            }
        });

        closeAdminAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rdphouses/close.png"))); // NOI18N
        closeAdminAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeAdminAdminMouseClicked(evt);
            }
        });

        BackTAdminHome.setBackground(new java.awt.Color(53, 66, 74));
        BackTAdminHome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BackTAdminHome.setForeground(java.awt.Color.white);
        BackTAdminHome.setText("Back");
        BackTAdminHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 74), 0));
        BackTAdminHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackTAdminHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackTAdminHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeAdminAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 278, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeAdminAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackTAdminHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(createAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAdminMouseClicked
        new AdminDelete().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteAdminMouseClicked

    private void createAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAdminMouseClicked
       
        new Administrator().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createAdminMouseClicked

    private void updateAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateAdminMouseClicked
        new AdminUpdates().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateAdminMouseClicked

    private void closeAdminAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeAdminAdminMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeAdminAdminMouseClicked

    private void BackTAdminHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackTAdminHomeMouseClicked
        new AdminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackTAdminHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackTAdminHome;
    private javax.swing.JLabel StatusBackTAdminHome;
    private javax.swing.JLabel StatusBackTAdminHome1;
    private javax.swing.JLabel StatusBackTAdminHome2;
    private javax.swing.JLabel StatusBackTAdminHome3;
    private javax.swing.JLabel closeAdminAdmin;
    private javax.swing.JLabel createAdmin;
    private javax.swing.JLabel deleteAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel updateAdmin;
    // End of variables declaration//GEN-END:variables
}
