/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rdphouses;

import javax.swing.JOptionPane;

/**
 *
 * @author tholithemba
 */
public class AdminUpdates extends javax.swing.JFrame implements IUpdates {

    RequiredFields req_field = new RequiredFields();
    /**
     * Creates new form AdminUpdates
     */
    public AdminUpdates() {
        initComponents();
    }    
    
    @Override
    public String setValues(){
        
        String selected_item = (String)fieldToUpdateSelected.getSelectedItem();
        
        req_field.setRFUsername(username_txt.getText());
        
        switch(selected_item){
            
            case "Firstname": req_field.setFieldName("admin_firstname");
                break;
            case "Lastname": req_field.setFieldName("admin_lastname");
                break;

            case "Email": req_field.setFieldName("admin_username");
                break;
            case "Password": req_field.setFieldName("admin_password");
                break;
                
            default:JOptionPane.showMessageDialog(null, "selection problem contact administrator");
                    System.exit(0);
                   break;
        }
        
        String query_statement = 
                "select "+req_field.getFieldName()+" from ADMINISTRATOR"
                + " where admin_username=?";
        
        return query_statement;
    }
    
    
    @Override
    public boolean validateInput(){
        boolean input_valid = true;
        
        if(fieldToUpdateSelected.getSelectedItem().equals("Select"))
            return outputStatement("select field you want to update");
        
        if(username_txt.getText().equals(""))
            return outputStatement("Enter username");
        
        return input_valid;
    }
    
    @Override
    public boolean outputStatement(String message){
        
        warning_txt.setText(message);
        clearCells();
        return false;
    }
    
    @Override
    public void clearCells(){
        
        username_txt.setText("");
        val_tobe_updated.setText("");
    }


    @Override
    public void warningTextInitialised(){
        warning_txt.setText("");
    }

    @Override
    public void selectedField(){
        
        String query = setValues();
        
        String fied_data = req_field.getDataTobeUpdated(query);
        
        if(fied_data != null){
            val_tobe_updated.setText(fied_data);
        }else{
            warning_txt.setText("username does not exist");
            clearCells();
        }
    }
    
    @Override
    public boolean modifiedTextFieldNotEmpty(){
        if(val_tobe_updated.getText().equals(""))
            return outputStatement("text field to be modified is empty");
        
        return true;
    }
    
    @Override
    public String queryStatement(){
        
        String query = 
        "update ADMINISTRATOR set "+req_field.getFieldName()+"=? where "+
                "admin_username=?";
        
        return query;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeAdminUpdates = new javax.swing.JLabel();
        fieldToUpdateSelected = new javax.swing.JComboBox<>();
        label2 = new java.awt.Label();
        val_tobe_updated = new java.awt.TextField();
        label3 = new java.awt.Label();
        username_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        warning_txt = new java.awt.Label();
        updateData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(53, 66, 74));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 74, 29), 3));

        closeAdminUpdates.setIcon(new javax.swing.ImageIcon("/home/tholithemba/Desktop/github/java/RDPhouses/close.png")); // NOI18N
        closeAdminUpdates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeAdminUpdatesMouseClicked(evt);
            }
        });

        fieldToUpdateSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Firstname", "Lastname", "Email", "Password" }));
        fieldToUpdateSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldToUpdateSelectedActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(java.awt.Color.white);
        label2.setText("Field to Modify");

        val_tobe_updated.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setForeground(java.awt.Color.white);
        label3.setText("Modify");

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Email");

        warning_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        warning_txt.setForeground(java.awt.Color.red);

        updateData.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        updateData.setForeground(new java.awt.Color(232, 74, 29));
        updateData.setText("Update");
        updateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeAdminUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(warning_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(val_tobe_updated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldToUpdateSelected, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(updateData)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeAdminUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(warning_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(val_tobe_updated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(fieldToUpdateSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(updateData)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeAdminUpdatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeAdminUpdatesMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeAdminUpdatesMouseClicked

    private void fieldToUpdateSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldToUpdateSelectedActionPerformed
        
        warningTextInitialised();
        if(!validateInput())return;
        
        selectedField();
    }//GEN-LAST:event_fieldToUpdateSelectedActionPerformed

    private void updateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDataMouseClicked
       
        warningTextInitialised();
        
        if(!validateInput())return;
        
        if(!modifiedTextFieldNotEmpty())return;
        
        req_field.setFieldData(val_tobe_updated.getText());
        req_field.addUpdatedData(queryStatement());
        
        clearCells(); 
    }//GEN-LAST:event_updateDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeAdminUpdates;
    private javax.swing.JComboBox<String> fieldToUpdateSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel updateData;
    private javax.swing.JTextField username_txt;
    private java.awt.TextField val_tobe_updated;
    private java.awt.Label warning_txt;
    // End of variables declaration//GEN-END:variables
}
