/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rdphouses;

import javax.swing.JOptionPane;

/**
 *
 * @author tholithemba
 */
public class ApplicantUpdates extends javax.swing.JFrame implements IUpdates {

    RequiredFields req_field = new RequiredFields();
    
    /**
     * Creates new form ApplicantUpdates
     */
    public ApplicantUpdates() {
        initComponents();
    }
    
    @Override
    public String setValues(){
        
        String selected_item = (String)fieldToUpdateSelected.getSelectedItem();
        
        req_field.setRFUsername(username_txt.getText());
        
        switch(selected_item){
            
            case "Firstname": req_field.setFieldName("applicant_fname");
                break;
            case "Lastname": req_field.setFieldName("applicant_lname");
                break;
            case "ID number": req_field.setFieldName("applicant_id_no");
                break;
            case "Contact": req_field.setFieldName("applicant_cell_no");
                break;                
            case "Email": req_field.setFieldName("applicant_email");
                break;
            case "Username": req_field.setFieldName("applicant_username");
                break;                
            case "Prefered Communication Medium": req_field.setFieldName("applicant_comm_medium");
                break;
                
            default:JOptionPane.showMessageDialog(null, "selection problem contact administrator");
                    System.exit(0);
                   break;
        }
        
        String query_statement = 
                "select "+req_field.getFieldName()+" from APPLICANT"
                + " where applicant_email=?";
        
        return query_statement;
    }
    
    
    @Override
    public boolean validateInput(){
        boolean input_valid = true;
        
        if(fieldToUpdateSelected.getSelectedItem().equals("Select"))
            return outputStatement("select field you want to update");
        
        if(username_txt.getText().equals(""))
            return outputStatement("Enter Email");
        
        return input_valid;
    }
    
    @Override
    public boolean outputStatement(String message){
        
        warning_txt.setText(message);
        clearCells();
        return false;
    }
    
    public void clearCells(){
        
        username_txt.setText("");
        val_tobe_updated.setText("");
    }


    public void warningTextInitialised(){
        warning_txt.setText("");
    }

    @Override
    public void selectedField(){
        
        String query = setValues();
        
        String fied_data = req_field.getDataTobeUpdated(query);
        
        if(fied_data != null){
            val_tobe_updated.setText(fied_data);
        }else{
            warning_txt.setText("username does not exist");
            clearCells();
        }
    }
    
    @Override
    public boolean modifiedTextFieldNotEmpty(){
        if(val_tobe_updated.getText().equals(""))
            return outputStatement("text field to be modified is empty");
        
        return true;
    }
    
    public String queryStatement(){
        
        String query = 
        "update APPLICANT set "+req_field.getFieldName()+"=? where "+
                "applicant_email=?";
        
        return query;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeApplicantUpdates = new javax.swing.JLabel();
        warning_txt = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        val_tobe_updated = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldToUpdateSelected = new javax.swing.JComboBox<>();
        updateApplicant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(53, 66, 74));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 73, 29), 3));

        closeApplicantUpdates.setIcon(new javax.swing.ImageIcon("/home/tholithemba/Desktop/github/java/RDPhouses/close.png")); // NOI18N
        closeApplicantUpdates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeApplicantUpdatesMouseClicked(evt);
            }
        });

        warning_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        warning_txt.setForeground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Modify");

        val_tobe_updated.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Select field to be updated");

        fieldToUpdateSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Firstname", "Lastname", "ID number", "Contact", "Email", "Prefered Communication Medium" }));
        fieldToUpdateSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldToUpdateSelectedActionPerformed(evt);
            }
        });

        updateApplicant.setBackground(new java.awt.Color(53, 66, 74));
        updateApplicant.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        updateApplicant.setForeground(new java.awt.Color(232, 73, 29));
        updateApplicant.setText("Update");
        updateApplicant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateApplicantMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeApplicantUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(warning_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fieldToUpdateSelected, javax.swing.GroupLayout.Alignment.LEADING, 0, 216, Short.MAX_VALUE)
                                .addComponent(val_tobe_updated, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username_txt, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(updateApplicant)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(closeApplicantUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(warning_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(val_tobe_updated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldToUpdateSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(updateApplicant)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeApplicantUpdatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeApplicantUpdatesMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeApplicantUpdatesMouseClicked

    private void fieldToUpdateSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldToUpdateSelectedActionPerformed
        
        warningTextInitialised();
        
        if(!validateInput())return;
        
        selectedField();
    }//GEN-LAST:event_fieldToUpdateSelectedActionPerformed

    private void updateApplicantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateApplicantMouseClicked
        
        warningTextInitialised();
        
        if(!validateInput())return;
        
        if(!modifiedTextFieldNotEmpty())return;
        
        req_field.setFieldData(val_tobe_updated.getText());
        req_field.addUpdatedData(queryStatement());
        
        clearCells();
    }//GEN-LAST:event_updateApplicantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantUpdates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantUpdates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeApplicantUpdates;
    private javax.swing.JComboBox<String> fieldToUpdateSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel updateApplicant;
    private javax.swing.JTextField username_txt;
    private javax.swing.JTextField val_tobe_updated;
    private java.awt.Label warning_txt;
    // End of variables declaration//GEN-END:variables
}
