/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rdphouses;

/**
 *
 * @author tholithemba
 */
public class FunderDelete extends javax.swing.JFrame {

    /**
     * Creates new form FunderDelete
     */
    public FunderDelete() {
        initComponents();
    }
    
    private boolean validateInput()
    {
        if(txtfunderUsername.getText().equals(""))
        {
            lblerror_text.setText("Enter Applicant username");
            return false;
        }
        
        return true;
    }
    
    private void setValue()
    {
        Registration reg = new Registration();
        reg.setUsername(txtfunderUsername.getText());
    }
    
    
    private boolean deleteFunder()
    {
        Crud crud = new Crud();
        String query = "delete from FUNDER where funder_email=?";
        boolean success = crud.deleteData(query);
        
        if(!success)
        {
            lblerror_text.setText("Applicant username does not exist");
            clearText();
            return success;
        }
        
        return success;
    }
    
    
    private void clearText()
    {
        txtfunderUsername.setText("");
    }
    
    private void clearErrorMessage()
    {
        lblerror_text.setText("");
    }

    
    private void successMessage()
    {
       lblerror_text.setText("data deleted successfully....");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        documents = new javax.swing.JPanel();
        closeFunderDelete = new javax.swing.JLabel();
        BackTAdminFunder = new javax.swing.JLabel();
        txtfunderUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btndeleteFunder = new javax.swing.JButton();
        lblerror_text = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        documents.setBackground(new java.awt.Color(53, 66, 74));
        documents.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 73, 29), 3));

        closeFunderDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rdphouses/close.png"))); // NOI18N
        closeFunderDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeFunderDeleteMouseClicked(evt);
            }
        });

        BackTAdminFunder.setBackground(new java.awt.Color(53, 66, 74));
        BackTAdminFunder.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BackTAdminFunder.setForeground(java.awt.Color.white);
        BackTAdminFunder.setText("Back");
        BackTAdminFunder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 74), 0));
        BackTAdminFunder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackTAdminFunderMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Username");

        btndeleteFunder.setBackground(java.awt.Color.red);
        btndeleteFunder.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btndeleteFunder.setForeground(java.awt.Color.white);
        btndeleteFunder.setText("Delete");
        btndeleteFunder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteFunderMouseClicked(evt);
            }
        });

        lblerror_text.setAlignment(java.awt.Label.CENTER);
        lblerror_text.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblerror_text.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout documentsLayout = new javax.swing.GroupLayout(documents);
        documents.setLayout(documentsLayout);
        documentsLayout.setHorizontalGroup(
            documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackTAdminFunder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 806, Short.MAX_VALUE)
                .addComponent(closeFunderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(documentsLayout.createSequentialGroup()
                .addGroup(documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documentsLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addGroup(documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfunderUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(documentsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btndeleteFunder, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(documentsLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(lblerror_text, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        documentsLayout.setVerticalGroup(
            documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentsLayout.createSequentialGroup()
                .addGroup(documentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeFunderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackTAdminFunder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lblerror_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfunderUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btndeleteFunder)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(documents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(documents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeFunderDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeFunderDeleteMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeFunderDeleteMouseClicked

    private void BackTAdminFunderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackTAdminFunderMouseClicked
        new AdminFunder().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackTAdminFunderMouseClicked

    private void btndeleteFunderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteFunderMouseClicked
       
        clearErrorMessage();
        if(!validateInput())return;
        setValue();
        if(!deleteFunder())return;
        successMessage();
        clearText();
    }//GEN-LAST:event_btndeleteFunderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunderDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunderDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunderDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunderDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunderDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackTAdminFunder;
    private javax.swing.JButton btndeleteFunder;
    private javax.swing.JLabel closeFunderDelete;
    private javax.swing.JPanel documents;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label lblerror_text;
    private javax.swing.JTextField txtfunderUsername;
    // End of variables declaration//GEN-END:variables
}
