/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinic_management;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author tholithemba
 */
public class UpdateDoctor extends javax.swing.JFrame {

    UpdateDataFields udf = new UpdateDataFields();
    UserRegistration user_reg = new UserRegistration();
    /**
     * Creates new form UpdateDoctor
     */
    public UpdateDoctor() {
        initComponents();
    }

    //set values
    private String setValues(){
        
        String selected_item = (String)fieldToUpdate.getSelectedItem();
        
        user_reg.setUsername(username_txt.getText());
        
        switch(selected_item){
            
            case "Firstname": udf.setHeadingName("NAME");
                break;
            case "Lastname": udf.setHeadingName("SURNAME");
                break;
            case "Specialization": udf.setHeadingName("SPECIALIZATION");
                break;
                
            default:JOptionPane.showMessageDialog(null, "selection problem contact administrator");
                    System.exit(0);
                   break;
        }
        
        String query_statement = "select "+udf.getHeadingName()+" from DOCTOR where PRACTICE_NUMBER=?";
        return query_statement;
    }
    //end setValues() method
    
    //validate input from the user
    private boolean validateInput(){
        boolean input_valid = true;
        if(fieldToUpdate.getSelectedItem().equals("Select"))
            return outputStatement("select field you want to update");
        
        if(username_txt.getText().equals(""))
            return outputStatement("Enter username");
        
        return input_valid;
    }
    
    //display error message
    private boolean outputStatement(String message){
        
        warning_msg.setText(message);
        return false;
    }
    
    //set data from database
    private boolean selectedField(){
        
        String query = setValues();
        String fied_data = udf.getDataTobeUpdated(query);
        
        if(fied_data != null){
            val_tobe_updated.setText(fied_data);
            return true;
        }else{
            warning_msg.setText("username does not exist");
            return false;
        }
    }
    
    //set and validate data to be updated
    private boolean setAndValidateUpdateField(){
        
        udf.setFieldData(val_tobe_updated.getText());
        if(udf.getFieldData().equals("")){
            warning_msg.setText("enter data to be updated");
            return false;
        }
        return true;
    }
    
    //write to database
    private void submitQuery(){
        
        String query_statement = "update DOCTOR set "+udf.getHeadingName()+"=? where PRACTICE_NUMBER=?";
        boolean updated = udf.addUpdatedData(query_statement);
        if(updated){
            warning_msg.setForeground(Color.green);
            warning_msg.setText("update was successfull....");
        }else{
            JOptionPane.showMessageDialog(null, "Please contact the administrator");
        }
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeUpdateDoctor = new javax.swing.JLabel();
        val_tobe_updated = new java.awt.TextField();
        UpdateDoctorData = new javax.swing.JButton();
        warning_msg = new java.awt.Label();
        fieldToUpdate = new javax.swing.JComboBox<>();
        username_txt = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        DoctorBackToRecptH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(25, 25, 112));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow, 3));

        closeUpdateDoctor.setIcon(new javax.swing.ImageIcon("/home/tholithemba/Desktop/github/java/RDPhouses/close.png")); // NOI18N
        closeUpdateDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeUpdateDoctorMouseClicked(evt);
            }
        });

        val_tobe_updated.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        UpdateDoctorData.setBackground(java.awt.Color.blue);
        UpdateDoctorData.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        UpdateDoctorData.setForeground(java.awt.Color.white);
        UpdateDoctorData.setText("Update");
        UpdateDoctorData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateDoctorDataMouseClicked(evt);
            }
        });

        warning_msg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        warning_msg.setForeground(java.awt.Color.red);

        fieldToUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Firstname", "Lastname", "Specialization" }));
        fieldToUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldToUpdateActionPerformed(evt);
            }
        });

        username_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("Practice Number");

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(java.awt.Color.white);
        label2.setText("Field to Modify");

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setForeground(java.awt.Color.white);
        label3.setText("Modify");

        DoctorBackToRecptH.setBackground(new java.awt.Color(53, 66, 74));
        DoctorBackToRecptH.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        DoctorBackToRecptH.setForeground(java.awt.Color.white);
        DoctorBackToRecptH.setIcon(new javax.swing.ImageIcon("/home/tholithemba/Desktop/github/java/RDPhouses/arrow.png")); // NOI18N
        DoctorBackToRecptH.setText("Back");
        DoctorBackToRecptH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 74), 0));
        DoctorBackToRecptH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorBackToRecptHMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorBackToRecptH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeUpdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warning_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(username_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(val_tobe_updated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldToUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateDoctorData, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38))))
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeUpdateDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorBackToRecptH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(warning_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(val_tobe_updated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(fieldToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(UpdateDoctorData)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeUpdateDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeUpdateDoctorMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeUpdateDoctorMouseClicked

    private void UpdateDoctorDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDoctorDataMouseClicked

        if(!validateInput())return;

        if(!setAndValidateUpdateField())return;

        submitQuery();
    }//GEN-LAST:event_UpdateDoctorDataMouseClicked

    private void fieldToUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldToUpdateActionPerformed

        if(!validateInput())return;

        if(!selectedField())return;
    }//GEN-LAST:event_fieldToUpdateActionPerformed

    private void DoctorBackToRecptHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorBackToRecptHMouseClicked

        new DoctorHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DoctorBackToRecptHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorBackToRecptH;
    private javax.swing.JButton UpdateDoctorData;
    private javax.swing.JLabel closeUpdateDoctor;
    private javax.swing.JComboBox<String> fieldToUpdate;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField username_txt;
    private java.awt.TextField val_tobe_updated;
    private java.awt.Label warning_msg;
    // End of variables declaration//GEN-END:variables
}
