/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinic_management;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author tholithemba
 */
public class UpdatePatient extends javax.swing.JFrame {

    UpdateDataFields update_data = new UpdateDataFields();
    UserRegistration user_reg = new UserRegistration();
    
    /**
     * Creates new form UpdateDatabase
     */
    public UpdatePatient() {
        initComponents();
    }
    
    //initialise values
    private String setValues(){
        
        String selected_item = (String)fieldToUpdate.getSelectedItem();
        
        user_reg.setUsername(username_txt.getText());
        
        switch(selected_item){
            
            case "Firstname": update_data.setHeadingName("NAME");
                break;
            case "Lastname": update_data.setHeadingName("SURNAME");
                break;
            case "ID/Passport number": update_data.setHeadingName("ID_OR_PASSORT_NUMBER");
                break;
            case "Date of birth": update_data.setHeadingName("DOB");
                break; 
            case "Occupation": update_data.setHeadingName("OCCUPATION");
                break;

            case "Contact": update_data.setHeadingName("MOBILE_NUMBER");
                break;

            case "Email": update_data.setHeadingName("EMAIL");
                break;
                
            default:JOptionPane.showMessageDialog(null, "selection problem contact administrator");
                    System.exit(0);
                   break;
        }
        
        String query_statement = "select "+update_data.getHeadingName()+" from PATIENT where EMAIL=?";
        return query_statement;
    }
    //end of setValues() method
    
    //validate input from the user
    private boolean validateInput(){
        boolean input_valid = true;
        if(fieldToUpdate.getSelectedItem().equals("Select"))
            return outputStatement("select field you want to update");
        
        if(username_txt.getText().equals(""))
            return outputStatement("Enter username");
        
        return input_valid;
    }
    
    //display error message
    private boolean outputStatement(String message){
        
        warning_msg.setText(message);
        return false;
    }
    
    //set data to be updated
    private boolean selectedField(){
        
        String query = setValues();
        String fied_data = update_data.getDataTobeUpdated(query);
        
        if(fied_data != null){
            val_tobe_updated.setText(fied_data);
            return true;
        }else{
            warning_msg.setText("username does not exist");
            return false;
        }
    }
    
    //set and validate field to be updated
    private boolean setAndValidateUpdateField(){
        
        update_data.setFieldData(val_tobe_updated.getText());
        if(update_data.getFieldData().equals("")){
            warning_msg.setText("enter data to be updated");
            return false;
        }
        return true;
    }
    
    //writes to the database
    private void submitQuery(){
        
        String query_statement = "update PATIENT set "+update_data.getHeadingName()+"=? where EMAIL=?";
        boolean updated = update_data.addUpdatedData(query_statement);
        if(updated){
            warning_msg.setForeground(Color.green);
            warning_msg.setText("update was successfull....");
        }else{
            JOptionPane.showMessageDialog(null, "Please contact the administrator");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeUpdateDatabase = new javax.swing.JLabel();
        val_tobe_updated = new java.awt.TextField();
        UpdateData = new javax.swing.JButton();
        warning_msg = new java.awt.Label();
        fieldToUpdate = new javax.swing.JComboBox<>();
        username_txt = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        PatientBackToPH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(25, 25, 112));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow, 3));

        closeUpdateDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic_management/close.png"))); // NOI18N
        closeUpdateDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeUpdateDatabaseMouseClicked(evt);
            }
        });

        val_tobe_updated.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        UpdateData.setBackground(java.awt.Color.blue);
        UpdateData.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        UpdateData.setForeground(java.awt.Color.white);
        UpdateData.setText("Update");
        UpdateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateDataMouseClicked(evt);
            }
        });

        warning_msg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        warning_msg.setForeground(java.awt.Color.red);

        fieldToUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Firstname", "Lastname", "ID/Passport number", "Date of birth", "Occupation", "Contact", "Email" }));
        fieldToUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldToUpdateActionPerformed(evt);
            }
        });

        username_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setText("Username");

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(java.awt.Color.white);
        label2.setText("Field to Modify");

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setForeground(java.awt.Color.white);
        label3.setText("Modify");

        PatientBackToPH.setBackground(new java.awt.Color(53, 66, 74));
        PatientBackToPH.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PatientBackToPH.setForeground(java.awt.Color.white);
        PatientBackToPH.setText("Back");
        PatientBackToPH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 66, 74), 0));
        PatientBackToPH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientBackToPHMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientBackToPH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeUpdateDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warning_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(username_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(val_tobe_updated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldToUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateData, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeUpdateDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientBackToPH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(warning_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(val_tobe_updated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(fieldToUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(UpdateData)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeUpdateDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeUpdateDatabaseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeUpdateDatabaseMouseClicked

    private void fieldToUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldToUpdateActionPerformed
       
       if(!validateInput())return;
        
       if(!selectedField())return;
    }//GEN-LAST:event_fieldToUpdateActionPerformed

    private void UpdateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateDataMouseClicked

        if(!validateInput())return;
        
        if(!setAndValidateUpdateField())return;
        
        submitQuery();
    }//GEN-LAST:event_UpdateDataMouseClicked

    private void PatientBackToPHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientBackToPHMouseClicked

        new PatientHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PatientBackToPHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PatientBackToPH;
    private javax.swing.JButton UpdateData;
    private javax.swing.JLabel closeUpdateDatabase;
    private javax.swing.JComboBox<String> fieldToUpdate;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField username_txt;
    private java.awt.TextField val_tobe_updated;
    private java.awt.Label warning_msg;
    // End of variables declaration//GEN-END:variables
}
